###

GET http://localhost:8080/summary

###

GET http://localhost:8080/summary/lazy

###

POST http://localhost:8080/signed-url
Content-Type: application/json

{
  "s3ObjectName": "task01/360FBD2E-D88F-4A11-B78A-62EC87CE28F5.jpeg"
}
